"""
Vendor register — and the one word this module must never misuse.

NEEM asked to verify tax IDs and bank accounts. Those two checks are not
equivalent and the tests exist mostly to keep them apart:

  * A BANK check is a real external verification. The bank tells us the name on
    the account. A diverted-payment fraud fails it.
  * A TIN check, with no provider configured, is a regular expression. It
    proves the number is well-formed. It proves nothing about whether the
    number exists or belongs to this vendor.

If a format check were ever reported as "verified", an auditor asking "did you
verify their TIN?" would get a yes generated by a regex. So a large share of
what follows is about that distinction surviving.

Run: python test_vendors.py
"""
from __future__ import annotations

import os
import shutil
import tempfile

_TMP = tempfile.mkdtemp(prefix="docex-vendors-")

import store  # noqa: E402

store.set_store(store.JsonFileStore(_TMP))

import vendors as vd  # noqa: E402

ORG = "vendortest"
_passed = _failed = 0


def check(label: str, cond: bool, detail: str = "") -> None:
    global _passed, _failed
    if cond:
        _passed += 1
        print(f"  ok   {label}")
    else:
        _failed += 1
        print(f"  FAIL {label}{(' — ' + detail) if detail else ''}")


def raises(label: str, fn, *, contains: str = "") -> None:
    try:
        fn()
    except vd.VendorError as exc:
        check(label, not contains or contains.lower() in str(exc).lower(), str(exc))
    except Exception as exc:                               # noqa: BLE001
        check(f"{label} (wrong exception: {type(exc).__name__}: {exc})", False)
    else:
        check(f"{label} (nothing raised)", False)


def clear() -> None:
    for v in store.get_store().list(ORG, "vendors"):
        store.get_store().delete(ORG, "vendors", v["id"])


# ─── tax id ─────────────────────────────────────────────────────────────────


def test_tin_format_checking() -> None:
    print("\nTIN format: catch the typo, claim nothing more")
    ok = vd.check_tin_format("12345678-0001")
    check("a valid 8+4 TIN passes format", ok.status == vd.VerificationStatus.FORMAT_OK)
    check("10 digits pass",
          vd.check_tin_format("1234567890").status == vd.VerificationStatus.FORMAT_OK)
    check("spaces and punctuation are tolerated",
          vd.check_tin_format(" 1234 5678-0001 ").tin == "12345678-0001")

    check("too short is rejected",
          vd.check_tin_format("12345").status == vd.VerificationStatus.INVALID)
    check("letters are rejected",
          vd.check_tin_format("ABCDEFGHIJ").status == vd.VerificationStatus.INVALID)

    # The two mistakes people actually make.
    phone = vd.check_tin_format("08031234567")
    check("a Nigerian mobile number is caught",
          phone.status == vd.VerificationStatus.INVALID)
    check("and named as such", "mobile number" in phone.message)

    filler = vd.check_tin_format("0000000000")
    check("all-identical digits are caught",
          filler.status == vd.VerificationStatus.INVALID)
    check("and called a placeholder", "placeholder" in filler.message)

    check("an empty TIN is unchecked, not invalid",
          vd.check_tin_format("").status == vd.VerificationStatus.UNCHECKED)


def test_a_format_check_is_never_called_verified() -> None:
    print("\nTHE IMPORTANT ONE: a regex is not a verification")
    ok = vd.check_tin_format("1234567890")
    check("status is format_ok, NOT verified",
          ok.status == vd.VerificationStatus.FORMAT_OK)
    check("externally_verified is False", ok.externally_verified is False)
    check("the message says it was not checked with the authority",
          "NOT been checked against the tax authority" in ok.message)
    check("no registered name is invented", ok.registered_name == "")

    # And with no provider configured, verify_tin must not upgrade it.
    os.environ.pop("DOCEX_TIN_PROVIDER", None)
    os.environ.pop("DOCEX_TIN_API_KEY", None)
    check("no lookup provider configured", vd.tin_lookup_available() is False)
    result = vd.verify_tin("1234567890")
    check("verify_tin still only format-checks",
          result.status == vd.VerificationStatus.FORMAT_OK)
    check("and still says so", result.externally_verified is False)


def test_a_configured_provider_is_reported_honestly() -> None:
    print("\nWith a provider configured but unimplemented, say that")
    os.environ["DOCEX_TIN_PROVIDER"] = "dojah"
    os.environ["DOCEX_TIN_API_KEY"] = "test-key"
    try:
        check("availability reflects config", vd.tin_lookup_available() is True)
        r = vd.verify_tin("1234567890")
        check("it does not pretend to have looked it up",
              r.externally_verified is False)
        check("and the message names the gap", "not implemented" in r.message)
    finally:
        os.environ.pop("DOCEX_TIN_PROVIDER", None)
        os.environ.pop("DOCEX_TIN_API_KEY", None)


# ─── bank account ───────────────────────────────────────────────────────────


def test_bank_account_shape_is_checked_before_calling_out() -> None:
    print("\nA malformed account number never reaches the bank")
    r = vd.verify_bank_account("Acme Ltd", "12345", "058")
    check("rejected locally", r.status == vd.VerificationStatus.INVALID)
    check("with the reason", "10 digits" in r.message)


def test_bank_name_matching() -> None:
    print("\nComparing the bank's name to ours")
    import bank_verify
    original = bank_verify.resolve_account
    try:
        bank_verify.resolve_account = lambda acct, code, **kw: ("ACME LIMITED", None)
        r = vd.verify_bank_account("Acme Ltd", "0123456789", "058")
        check("a company-suffix difference still verifies",
              r.status == vd.VerificationStatus.VERIFIED, r.message)
        check("the bank's own name is recorded", r.resolved_name == "ACME LIMITED")

        # The finding that matters: a genuine invoice, an altered account.
        bank_verify.resolve_account = lambda acct, code, **kw: ("JOHN A OKAFOR", None)
        r = vd.verify_bank_account("Acme Ltd", "0123456789", "058")
        check("a completely different name is a MISMATCH",
              r.status == vd.VerificationStatus.MISMATCH)
        check("and the message says not to pay", "Do not pay" in r.message)
        check("naming what the bank actually holds", "JOHN A OKAFOR" in r.message)

        bank_verify.resolve_account = lambda acct, code, **kw: (None, "Network error")
        r = vd.verify_bank_account("Acme Ltd", "0123456789", "058")
        check("an unreachable bank is unverifiable, not verified",
              r.status == vd.VerificationStatus.UNVERIFIABLE)
        check("carrying the reason", "Network error" in r.message)
    finally:
        bank_verify.resolve_account = original


# ─── the register ───────────────────────────────────────────────────────────


def test_creating_a_vendor() -> None:
    print("\nAdding a vendor format-checks the TIN immediately")
    clear()
    v = vd.create(ORG, name="Acme Ltd", tin="12345678-0001", created_by="a@org")
    check("created", v.id and v.name == "Acme Ltd")
    check("TIN normalised and checked", v.tax.status == vd.VerificationStatus.FORMAT_OK)
    check("not payment ready — no bank check yet", v.payment_ready is False)
    check("and not fully verified", v.fully_verified is False)

    raises("a duplicate name is refused",
           lambda: vd.create(ORG, name="ACME LIMITED"),
           contains="already in the register")
    check("because the register matches on the normalised name",
          vd.find_by_name(ORG, "acme  ltd.") is not None)


def test_verification_makes_a_vendor_payment_ready() -> None:
    print("\nA verified bank account is what unlocks payment")
    clear()
    v = vd.create(ORG, name="Acme Ltd", tin="1234567890")
    import bank_verify
    original = bank_verify.resolve_account
    try:
        bank_verify.resolve_account = lambda acct, code, **kw: ("ACME LIMITED", None)
        v = vd.run_checks(ORG, v.id, account_number="0123456789",
                          bank_code="058", checked_by="a@org")
        check("bank verified", v.bank.status == vd.VerificationStatus.VERIFIED)
        check("payment ready", v.payment_ready is True)
        # Payment-ready does NOT require a TIN lookup nobody can perform.
        check("but not 'fully verified' — the TIN was never looked up",
              v.fully_verified is False)
    finally:
        bank_verify.resolve_account = original


def test_blocking() -> None:
    print("\nBlocking a vendor requires a reason and keeps it")
    clear()
    v = vd.create(ORG, name="Dodgy Supplies")
    raises("a blank reason is refused",
           lambda: vd.block(ORG, v.id, reason="   "),
           contains="written reason")
    v = vd.block(ORG, v.id, reason="Under investigation", actor="ed@org")
    check("blocked", v.blocked is True)
    check("the reason names who and when",
          "Under investigation" in v.blocked_reason and "ed@org" in v.blocked_reason)
    check("blocked vendors are not payment ready", v.payment_ready is False)
    check("unblock clears it", vd.unblock(ORG, v.id).blocked is False)


def test_summary_does_not_overclaim() -> None:
    print("\nThe register summary keeps the two checks separate")
    clear()
    vd.create(ORG, name="Acme Ltd", tin="1234567890")
    vd.create(ORG, name="Beta Ltd", tin="08031234567")   # a phone number
    s = vd.register_summary(ORG)
    check("counts vendors", s["total"] == 2)
    check("counts TINs present", s["tin_present"] == 2)
    check("flags the invalid one", s["tin_invalid"] == 1)
    check("reports ZERO externally verified TINs",
          s["tin_externally_verified"] == 0)
    check("and says no lookup provider is configured",
          s["tin_lookup_configured"] is False)
    check("nobody is payment ready yet", s["payment_ready"] == 0)


def test_org_scoping() -> None:
    print("\nOne org cannot see another's vendors")
    clear()
    vd.create(ORG, name="Mine Ltd")
    vd.create("other-org", name="Theirs Ltd")
    check("scoped", [v.name for v in vd.list_vendors(ORG)] == ["Mine Ltd"])


# ─── the policy check on a requisition ──────────────────────────────────────


def test_the_requisition_check() -> None:
    print("\nA payment to a mismatched account is BLOCKED, not warned about")
    clear()
    import org_config
    store.get_store().put(ORG, "config", "features",
                          {"modules": ["compliance"],
                           "features": {"vendor_register": True}})

    import requisitions as rq

    v = vd.create(ORG, name="Acme Ltd", tin="1234567890")
    import bank_verify
    original = bank_verify.resolve_account
    try:
        bank_verify.resolve_account = lambda acct, code, **kw: ("JOHN A OKAFOR", None)
        vd.run_checks(ORG, v.id, account_number="0123456789", bank_code="058")

        req = rq.Requisition(id="x", org_id=ORG, vendor_name="Acme Ltd",
                             amount=50_000, category="supplies",
                             project_code="P1", documents=["invoice"])
        checks = rq.run_policy_checks(ORG, req)
        vc = next((c for c in checks if c.code == "VENDOR_VERIFIED"), None)
        check("the check ran", vc is not None)
        check("and it BLOCKS", vc.result == rq.CheckResult.FAIL, str(vc))
        check("naming the account holder the bank has",
              "JOHN A OKAFOR" in vc.message)

        # An unknown payee is a warning, not a block.
        req.vendor_name = "Someone Unknown Ltd"
        checks = rq.run_policy_checks(ORG, req)
        vc = next(c for c in checks if c.code == "VENDOR_VERIFIED")
        check("an unregistered payee only warns",
              vc.result == rq.CheckResult.WARNING)
        check("and says what to do", "Add them" in vc.message)

        # Verified vendor → pass, with the TIN caveat stated.
        bank_verify.resolve_account = lambda acct, code, **kw: ("ACME LIMITED", None)
        vd.run_checks(ORG, v.id, account_number="0123456789", bank_code="058")
        req.vendor_name = "Acme Ltd"
        vc = next(c for c in rq.run_policy_checks(ORG, req)
                  if c.code == "VENDOR_VERIFIED")
        check("a verified vendor passes", vc.result == rq.CheckResult.PASS)
        check("and the TIN caveat is still stated plainly",
              "not confirmed with the authority" in vc.message, vc.message)
    finally:
        bank_verify.resolve_account = original


def test_the_check_is_silent_when_not_adopted() -> None:
    print("\nAn org that has not adopted the register sees nothing")
    import requisitions as rq
    store.get_store().put("quiet-org", "config", "features",
                          {"modules": ["compliance"], "features": {}})
    req = rq.Requisition(id="x", org_id="quiet-org", vendor_name="Anyone Ltd",
                         amount=50_000, category="supplies", project_code="P1")
    checks = rq.run_policy_checks("quiet-org", req)
    check("no vendor check at all",
          not [c for c in checks if c.code == "VENDOR_VERIFIED"])


def main() -> int:
    print("=" * 66)
    print("Vendor register — verify the payee before the money moves")
    print("=" * 66)
    for fn in (
        test_tin_format_checking,
        test_a_format_check_is_never_called_verified,
        test_a_configured_provider_is_reported_honestly,
        test_bank_account_shape_is_checked_before_calling_out,
        test_bank_name_matching,
        test_creating_a_vendor,
        test_verification_makes_a_vendor_payment_ready,
        test_blocking,
        test_summary_does_not_overclaim,
        test_org_scoping,
        test_the_requisition_check,
        test_the_check_is_silent_when_not_adopted,
    ):
        fn()
    print("\n" + "=" * 66)
    print(f"{_passed} passed, {_failed} failed")
    print("=" * 66)
    return 1 if _failed else 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    finally:
        shutil.rmtree(_TMP, ignore_errors=True)
